### ISSUE TITLE
Error message when trying to install: Failed to build pretalx-pages

### ISSUE THREAD

**Issue by saschafoerster** [pretalx/pretalx-pages#3]
Pretalx is running in a docker container. I joined the bash of the container with the regular pretalxuser as well as with root, it is always the same error message: 
```

root@f36e54c0dbcf:/# pip install pretalx-pages
Collecting pretalx-pages
  Using cached pretalx-pages-1.0.0.tar.gz (7.5 kB)
Building wheels for collected packages: pretalx-pages
  Building wheel for pretalx-pages (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /usr/local/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-dpgv9w6h/pretalx-pages/setup.py'"'"'; __file__='"'"'/tmp/pip-install-dpgv9w6h/pretalx-pages/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-8xad6di3
       cwd: /tmp/pip-install-dpgv9w6h/pretalx-pages/
  Complete output (29 lines):
  running bdist_wheel
  running build
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-install-dpgv9w6h/pretalx-pages/setup.py", line 41, in <module>
      """,
    File "/usr/local/lib/python3.6/site-packages/setuptools/__init__.py", line 161, in setup
      return distutils.core.setup(**attrs)
    File "/usr/local/lib/python3.6/distutils/core.py", line 148, in setup
      dist.run_commands()
    File "/usr/local/lib/python3.6/distutils/dist.py", line 955, in run_commands
      self.run_command(cmd)
    File "/usr/local/lib/python3.6/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/usr/local/lib/python3.6/site-packages/wheel/bdist_wheel.py", line 223, in run
      self.run_command('build')
    File "/usr/local/lib/python3.6/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/usr/local/lib/python3.6/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/tmp/pip-install-dpgv9w6h/pretalx-pages/setup.py", line 18, in run
      management.call_command("compilemessages", verbosity=1)
    File "/usr/local/lib/python3.6/site-packages/django/core/management/__init__.py", line 148, in call_command
      return command.execute(*args, **defaults)
    File "/usr/local/lib/python3.6/site-packages/django/core/management/base.py", line 364, in execute
      output = self.handle(*args, **options)
    File "/usr/local/lib/python3.6/site-packages/django/core/management/commands/compilemessages.py", line 76, in handle
      raise CommandError("This script should be run from the Django Git "
  django.core.management.base.CommandError: This script should be run from the Django Git checkout or your project or app tree, or with the settings module specified.
  ----------------------------------------
  ERROR: Failed building wheel for pretalx-pages
  Running setup.py clean for pretalx-pages
Failed to build pretalx-pages
Installing collected packages: pretalx-pages
    Running setup.py install for pretalx-pages ... error
    ERROR: Command errored out with exit status 1:
     command: /usr/local/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-dpgv9w6h/pretalx-pages/setup.py'"'"'; __file__='"'"'/tmp/pip-install-dpgv9w6h/pretalx-pages/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-k5kzdpqh/install-record.txt --single-version-externally-managed --compile --install-headers /usr/local/include/python3.6m/pretalx-pages
         cwd: /tmp/pip-install-dpgv9w6h/pretalx-pages/
    Complete output (31 lines):
    running install
    running build
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-dpgv9w6h/pretalx-pages/setup.py", line 41, in <module>
        """,
      File "/usr/local/lib/python3.6/site-packages/setuptools/__init__.py", line 161, in setup
        return distutils.core.setup(**attrs)
      File "/usr/local/lib/python3.6/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/usr/local/lib/python3.6/distutils/dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "/usr/local/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/usr/local/lib/python3.6/site-packages/setuptools/command/install.py", line 61, in run
        return orig.install.run(self)
      File "/usr/local/lib/python3.6/distutils/command/install.py", line 545, in run
        self.run_command('build')
      File "/usr/local/lib/python3.6/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/local/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/tmp/pip-install-dpgv9w6h/pretalx-pages/setup.py", line 18, in run
        management.call_command("compilemessages", verbosity=1)
      File "/usr/local/lib/python3.6/site-packages/django/core/management/__init__.py", line 148, in call_command
        return command.execute(*args, **defaults)
      File "/usr/local/lib/python3.6/site-packages/django/core/management/base.py", line 364, in execute
        output = self.handle(*args, **options)
      File "/usr/local/lib/python3.6/site-packages/django/core/management/commands/compilemessages.py", line 76, in handle
        raise CommandError("This script should be run from the Django Git "
    django.core.management.base.CommandError: This script should be run from the Django Git checkout or your project or app tree, or with the settings module specified.
    ----------------------------------------
ERROR: Command errored out with exit status 1: /usr/local/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-dpgv9w6h/pretalx-pages/setup.py'"'"'; __file__='"'"'/tmp/pip-install-dpgv9w6h/pretalx-pages/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-k5kzdpqh/install-record.txt --single-version-externally-managed --compile --install-headers /usr/local/include/python3.6m/pretalx-pages Check the logs for full command output.
```

**Comment by rixx** [comment]
I just pushed a new release that should resolve this issue. Thank you for reporting it!

**Comment by saschafoerster** [comment]
Sorry, there comes another error message :) 

```
docker exec -it pretalx pretalx migrate
┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃ ┏━━━━━━━━━━┓  pretalx v1.1.2                        ┃
┃ ┃  ┌─·──╮  ┃  Settings:  /etc/pretalx/pretalx.cfg   ┃
┃ ┃  │  O │  ┃  Database:  pretalx (mysql)            ┃
┃ ┃  │ ┌──╯  ┃  Logging:   /data/logs                 ┃
┃ ┃  └─┘     ┃  Root dir:  /pretalx/src/pretalx       ┃
┃ ┗━━━┯━┯━━━━┛  Python:    /usr/local/bin/python3     ┃
┃     ╰─╯       Plugins:   pretalx_pages              ┃
┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/pretalx/src/pretalx/__main__.py", line 9, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.6/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.6/site-packages/django/core/management/__init__.py", line 357, in execute
    django.setup()
  File "/usr/local/lib/python3.6/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/lib/python3.6/site-packages/django/apps/registry.py", line 122, in populate
    app_config.ready()
  File "/src/pretalx-pages/pretalx_pages/__init__.py", line 19, in ready
    from . import signals  # NOQA
  File "/src/pretalx-pages/pretalx_pages/signals.py", line 6, in <module>
    from pretalx.common.signals import activitylog_display
ImportError: cannot import name 'activitylog_display'
┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃ ┏━━━━━━━━━━┓  pretalx v1.1.2                        ┃
┃ ┃  ┌─·──╮  ┃  Settings:  /etc/pretalx/pretalx.cfg   ┃
┃ ┃  │  O │  ┃  Database:  pretalx (mysql)            ┃
┃ ┃  │ ┌──╯  ┃  Logging:   /data/logs                 ┃
┃ ┃  └─┘     ┃  Root dir:  /pretalx/src/pretalx       ┃
┃ ┗━━━┯━┯━━━━┛  Python:    /usr/local/bin/python3     ┃
┃     ╰─╯       Plugins:   pretalx_pages              ┃
┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/pretalx/src/pretalx/__main__.py", line 9, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.6/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.6/site-packages/django/core/management/__init__.py", line 357, in execute
    django.setup()
  File "/usr/local/lib/python3.6/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/lib/python3.6/site-packages/django/apps/registry.py", line 122, in populate
    app_config.ready()
  File "/src/pretalx-pages/pretalx_pages/__init__.py", line 19, in ready
    from . import signals  # NOQA
  File "/src/pretalx-pages/pretalx_pages/signals.py", line 6, in <module>
    from pretalx.common.signals import activitylog_display
ImportError: cannot import name 'activitylog_display'
```

**Comment by rixx** [comment]
Yes, this is because `pretalx-pages` is currently only compatible with the development version of pretalx, not with v1.1.2.
